package: watson
version: '3.0.0-dev'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:watson'
    perm: watson[]
    pjax: false
    icon: watson-navigation-icon
    subpages:
        settings: { title: 'translate:config' }

requires:
    php:
        version: '>=8.1, <9'

providers:
    - 'Watson\Workflows\Structure\StructureProvider'
    - 'Watson\Workflows\Media\MediaProvider'
    - 'Watson\Workflows\Module\ModuleProvider'
    - 'Watson\Workflows\Template\TemplateProvider'
    - 'Watson\Workflows\Sprog\SprogProvider'
    - 'Watson\Workflows\YForm\YFormProvider'

stylesheets:
    - watson.css

javascripts:
    - watson.js
